//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutuphane
{
    using System;
    using System.Collections.Generic;
    
    public partial class kulveri
    {
        public int kul_id { get; set; }
        public string kul_ad { get; set; }
        public string kul_soyad { get; set; }
        public string kul_tc { get; set; }
        public string kul_tel { get; set; }
    }
}
